feat: plan Journey
rosvik/raycast-public-transport pull request #11
Opened 2024-12-30 11:08 UTC by binarybaba

Helps user plan a journey
This is for people like me who likes to check commute distance very frequently.

> While writing this, a lot of code was duplicated from the original `SearchPage`. There is a serious need for refactor. I didn't want to do it straightaway and risk touching other parts of the code as well. However, if this feature is merged (or if we wanna do this in _this_ PR?), we could do some significant improvements and refacors

### Screenshots
<img width="781" alt="image" src="https://github.com/user-attachments/assets/95226495-d8b3-43a6-ab7a-45860bcf278f" />
<img width="898" alt="image" src="https://github.com/user-attachments/assets/9e3ad2c8-d7f5-4db2-bfa4-2d3b642955b9" />
<img width="805" alt="image" src="https://github.com/user-attachments/assets/446c1f41-f1b9-433b-896d-87049d789836" />
<img width="772" alt="image" src="https://github.com/user-attachments/assets/b58511b4-56ac-4c1b-97e4-fbd26fbcefaa" />

implements #10

2025-01-02 19:10 UTC, binarybaba commented
@rosvik Lemme know if you think I should improve things in this PR or take it up in a follow up 🙌

2025-01-02 20:14 UTC, rosvik commented
@binarybaba I've been wanting to add trip search to the extension for a while now, but never gotten around to it, so I really appreciate you making this 💯 I've played around with it a bit now, and it works great! I'm looking over the code, and will get back to you ASAP with some minor comments.

For now, I wonder if you agree that we can make one simplification on the flow (from #10):

> Page: Flip direction + Leave At/Arrive By + Time

This far, I've thought that the most common use case for the extension would be users that need a quick way to check when the next bus/tram would leave a nearby stop. (e.g. someone about to leave work and want to see if their bus is delayed) Which I think is where Raycast shines: as a fast way to get info, and not necessarily the most feature complete solution. No way we can compete with entur.no on the amount of features, but we might be able to compete on ease of use and speed 🔥

So with this in mind, I think we should drop the settings page, and just have

- Page: search for Origin
- Page: search for Destination
- Page: Results + Details

Maybe there are ways to fit the reverse and time selection options on the results page, with a [Dropdown in the search bar](https://developers.raycast.com/api-reference/user-interface/list#list.dropdown) to select departure time and an [Action](https://developers.raycast.com/api-reference/user-interface/actions) to flip direction.

2025-01-02 21:33 UTC, rosvik requested changes
First of all, this is so cool! I love that you were able to fit most of a travel planner in a quite simple Raycast command ✨ I did spot a few points that can be improved, but I'm exited about merging this and and iterating on it further. Initially, I think I'll publish this as a private extension at my org, so I can get feedback from colleagues before it's sent to the Raycast Store.

In addition to the comments below, I noticed there are a few linting issues that can be fixed automatically by running `npm run lint -- --fix`.

2025-01-02 21:33 UTC, rosvik commented on package.json
> +      "description": "Plan for trips using public transportation in Norway",
```suggestion
      "description": "Get trip suggestions using public transportation in Norway",
```

2025-01-02 21:33 UTC, rosvik commented on package.json
> +      "title": "Plan Trip",
I think "Trip Search" is a bit more specific here.

```suggestion
      "title": "Trip Search",
```

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/AddTripDetails.tsx
As mentioned above, I think we should skip this page, and maybe look for alternative ways to add these features in the future.

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/Trip.tsx
> +      icon: getTransportIcon(leg.mode),
We should also send in `leg.transportSubmode` here.

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/Trip.tsx
> +  const accessories = trip.legs
Setting the type explicitly here should remove the need for `// @ts-expect-error` below.

```suggestion
  const accessories: Accessory[] = trip.legs
```

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/Trip.tsx
> +    // @ts-expect-error Tags _do_ exist
```suggestion
```

2025-01-02 21:33 UTC, rosvik commented on src/utils.ts
> +const FootIcon: Image = { source: "transport-modes/Foot.svg", tintColor: Color.PrimaryText };
This svg is very similar to the built in `Icon.Footprints` icon. Not sure what's best, but we should use that or [`WalkIcon` from Enturs design system](https://design.entur.no/komponenter/ressurser/icons).

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/SearchStartVenue.tsx
> +      searchBarPlaceholder="Search for departing place"
What about using these placeholders:
- `Find trip from...` on this page
- `Find trip from {from place} to...` on SearchDestinationPage
- And `From {from place} to {to place}...` on the Trip page. (Which should probably be something like "Filter by mode, line, etc..." once we add keywords to filter by)

2025-01-02 21:33 UTC, rosvik commented on src/hooks/use-debounced-venues.ts
I think this could stay in the Search directory for now. Since it will probably change anyway when we deduplicate the search pages.

2025-01-02 21:33 UTC, rosvik commented on src/journeyQuery.ts
> +  query planTrip($fromPlace: String, $toPlace: String, $numTripPatterns: Int, $dateTime: DateTime, $arriveBy: Boolean, $pageCursor: String){
Excuse the nitpick 🙈 But since it won't be fixed by eslint:

```suggestion
query planTrip($fromPlace: String, $toPlace: String, $numTripPatterns: Int, $dateTime: DateTime, $arriveBy: Boolean, $pageCursor: String) {
```

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/Trip.tsx
> +          // TODO: subtitle => "Little warning triangle if service disruptions are present"
Good point ⚠️ This applies to the departures command as well. Made an issue for it here https://github.com/rosvik/raycast-public-transport/issues/13

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/Trip.tsx
> +      text: `${leg.line ? leg.line?.publicCode : ""}`,
Can simplify this a bit, which also fixes a bug for public code `null`

```suggestion
      text: leg.line?.publicCode,
```

2025-01-02 21:33 UTC, rosvik commented on src/journeyQuery.ts
> +        aimedEndTime
We should use `expectedStartTime` and `expectedEndTime` here, to get real-time adjusted estimates.

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/Trip.tsx
> +            text={getLabelText(leg)}
I realize it's hard to fit all the information we need here, but here's a suggestion:

- We should show estimated departure times for each leg, since the trip start and end only tell part of the story.
- I think we should show the line name / frontText as well. See `formatDestinationDisplay()` in utils.
- Instead of only stop name, I think we should show the quays public code as well. When we do, I think the "correct" way is to show quay name as well. So from journey planner, we get `fromPlace.quay.name` and `fromPlace.quay.publicCode` instead of `fromPlace.name`.

A solution could look something like this, where the last line only shows destination name and time of arrival:

```
13:33 Jernbanetorget                     🚶‍♂️ 300 meters (4 mins)
13:37 Oslo S 11                 🚆 FLY2 Oslo Lufthavn (22 mins)
13:59 Oslo lufthavn stasjon 2
```

That being said, I'm ok with merging your solution, then we can iterate towards a different solution afterwards 😊

2025-01-02 21:33 UTC, rosvik commented on src/PlanTrip/Trip.tsx
> +            icon={getTransportIcon(leg.mode)}
Same as above, also provide `leg.transportSubmode`

2025-01-02 21:33 UTC, rosvik commented on src/api.ts
> +      numTripPatterns: 10,
I don't think we need to set `numTripPatterns` for our use case. Showing more than 10 suggestions shouldn't be a problem, and I'm more in favor of relying on defaults. 

From Enturs docs:

> The maximum number of trip patterns to return. Note! This reduce the number of trip patterns AFTER the OTP travel search is done in a post-filtering process. There is little/no performance gain in reducing the number of trip patterns returned.

```suggestion
```

2025-01-03 15:17 UTC, binarybaba commented on src/PlanTrip/Trip.tsx
> +            text={getLabelText(leg)}
Choosing this message to reply. Wonderful review!

At a glance, I agree with everything. Good stuff to do on the coming weekend :D 

But this one in particular I absolutely love! I didn't really see the quays and was a bit confused as to what they actually represent.

I'm gonna go over and reply to you in other comments possibly as I go. 

But yes, let's wait and lemme get the changes in. Then we can have it beta tested at your org 💪

2025-01-03 15:28 UTC, binarybaba commented on package.json
> +      "title": "Plan Trip",
> **Command title**
> Usually it's `<verb> <noun>` structure or just `<noun>`
> The best approach is to see how other commands are named in Raycast to get inspiration
> ✅ `Search Recent Projects`, `Translate`, `Open Issues`, `Create Task`
> ❌ `Recent Projects Search`, `Translation`, `New Task`
 
-- from [raycast's guide](https://developers.raycast.com/basics/prepare-an-extension-for-store#extensions-and-commands-naming)

Maybe `Search Trip`?

2025-01-03 15:36 UTC, binarybaba commented on src/utils.ts
> +const FootIcon: Image = { source: "transport-modes/Foot.svg", tintColor: Color.PrimaryText };
I really like the icon set you're using. They seem to me as part of a design system. Any chance there is a walk icon in it? If yes maybe we can use that? If not, probably then we can go with entur's?

2025-01-03 18:11 UTC, rosvik commented on package.json
> +      "title": "Plan Trip",
Ah, thanks for looking up the guidelines! I'm more used to saying "Trip Search", but I guess it's better to be in line with other commands 👍 We should probably use plural tho, in line with other commands like "Search Notes" and "Search Snippets".

```suggestion
      "title": "Search Trips",
```

2025-01-03 18:30 UTC, rosvik commented on src/utils.ts
> +const FootIcon: Image = { source: "transport-modes/Foot.svg", tintColor: Color.PrimaryText };
I believe all the icons are from Enturs design system. The advantage of using those instead of Raycast built-ins are consistency with other Norwegian travel planners, so on second thought, I'm also in favor of using the Walk icon from there 👍

Here's a cleaned up SVG we can use: [Foot.svg](https://github.com/user-attachments/assets/de40e3e0-003e-49dd-a4bd-67be892323a7)

2025-01-04 14:52 UTC, binarybaba commented on src/utils.ts
> +const FootIcon: Image = { source: "transport-modes/Foot.svg", tintColor: Color.PrimaryText };
I think we should stick to consistency for sure.

While playing with their playground, I noticed that they also provide a Presentation key on each Line: 
```
"line": {
  "presentation": {
      "colour": "E60000"
   },
"id": "RUT:Line:87",
"transportMode": "bus",
```

And Raycast also has a [Raw Color](https://developers.raycast.com/api-reference/user-interface/colors#color.raw) kind which we can even explicitly tell [to adjust the contrast according to the UI](https://developers.raycast.com/api-reference/user-interface/colors#example-1). 

Wondering if we should use it for the Icons? (seperate PR for sure).

2025-01-04 14:55 UTC, binarybaba commented on src/PlanTrip/Trip.tsx
> +      text: `${leg.line ? leg.line?.publicCode : ""}`,
I was probably drunk when I wrote this line

2025-01-04 17:29 UTC, binarybaba commented
Getting rid of the details screen suddenly made so much more sense. Feels more _inline_. 🙌 

- It seems we can't have a Form.DatePicker in the search dropdown. I feel maybe we should think some more about it if we must implement it. 
- Same with flipping the direction

So I have removed them completely.
Idk without those this feels so much more succint and right! 🤷🏻

2025-01-05 12:00 UTC, rosvik reviewed
Awesome! This feels surprisingly nice to use now 😄

Noticed a couple of minor details while reading through this a second time. Other than that, this looks ready to merge 🚀

2025-01-05 12:00 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +                }}
```suggestion
                // TODO: Remove this in favor of `pagination` returned from
                // using the built-in useFetch/usePromise:
                // https://developers.raycast.com/utilities/react-hooks/usefetch#pagination
                onAction={getTrips}
```

2025-01-05 12:00 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +      text: `${leg.line?.publicCode || ""}`,
We can pass `undefined` or `null` here, so I don't think we should fall back to the empty string

```suggestion
      text: leg.line?.publicCode,
```

2025-01-05 12:00 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +  strategy: "arrive-by" | "leave-at";
This prop can be removed now that we don't have the settings page.

2025-01-05 12:00 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +    }
Not sure I understand why we're hiding `publicCode` in this case 🤔 Can these lines be removed?

2025-01-05 12:00 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +    .filter((leg) => !(leg.mode === "foot" && leg.fromPlace.name === leg.toPlace.name))
It's more precise to use stop ID for this. (We should be able to fetch `id` instead of `name` in the query)

```suggestion
    .filter((leg) => !(leg.mode === "foot" && leg.fromPlace.id === leg.toPlace.id))
```

2025-01-05 12:00 UTC, rosvik commented on src/utils.ts
> +const FootIcon: Image = { source: "transport-modes/Foot.svg", tintColor: Color.PrimaryText };
Oh, the colour field is interesting! Something to look into, but I'm concerned it will make it harder to distinguish some transport modes as a result. Ruter's red will probably look very similar to the red we use for trains.

2025-01-05 12:00 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +  const getTitleText = (leg: Leg, isArriveText?: boolean) => {
I'm more in favor of spitting this in two functions, e.g `getLegTitle` and `getDestinationTitle`. That might be slightly more readable.

2025-01-05 12:00 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +      dateTime,
Had to look a bit into it, but it looks like we can remove the `dateTime` parameter entirely for our use case! It defaults to "now", and when we pass a cursor, it already contains a date:

E.g. cursor 
```
MXxORVhUX1BBR0V8MjAyNS0wMS0wNVQxNDowNDo1NVp8fDFoMTBtfFNUUkVFVF9BTkRfQVJSSVZBTF9USU1FfHx8fHx8
``` 

is a base64 encoded string that decodes to 

```
1|NEXT_PAGE|2025-01-05T14:04:55Z||1h10m|STREET_AND_ARRIVAL_TIME||||||
```

2025-01-05 22:56 UTC, binarybaba commented on src/SearchTrips/Trip.tsx
> +    }
Only when it's a transfer between the same places. which is walking. but I guess when we have the quay, it makes sense to mention the publicCode. I've removed it 💪

2025-01-05 23:10 UTC, binarybaba commented on src/SearchTrips/Trip.tsx
> +    .filter((leg) => !(leg.mode === "foot" && leg.fromPlace.name === leg.toPlace.name))
`id` unfortunately doesn't exist in `Place`. It seems Place doesn't implement `PlaceInterface` 🤔

2025-01-06 09:38 UTC, rosvik commented on src/SearchTrips/Trip.tsx
> +    .filter((leg) => !(leg.mode === "foot" && leg.fromPlace.name === leg.toPlace.name))
Ah, my bad. We'll have to use `fromPlace.quay.stopPlace.id` then. (`quay.stopPlace` gives the parent stop place of the quay)

2025-01-06 15:06 UTC, rosvik approved these changes
Love it. I'm itching to get this merged so I can start using it myself, so I think I will 😄 Of course, feel free to make follow up PRs if you notice something you would like to change.

Thank you so much for making this 🚀

2025-01-06 15:06 UTC, merged

2025-01-08 09:52 UTC, binarybaba commented on src/SearchTrips/Trip.tsx
> +    .filter((leg) => !(leg.mode === "foot" && leg.fromPlace.name === leg.toPlace.name))
I'll pick this one up soon!